name: 'Create GitHub Commit'
description: 'Create Commit'
author: 'qoomon'
branding:
  icon: git-commit
  color: blue

inputs:
  add:
    description: 'add command arguments'
  commit:
    description: 'commit command arguments'
    required: true
  push:
    description: 'push command arguments'

  token:
    description: 'A GitHub access token'
    required: true
    default: ${{ github.token }}
  remoteName:
    description: 'The remote name to create the commit at.'
    required: true
    default: 'origin'

outputs:
  commit:
    description: 'The commit hash, if a commit was created'

runs:
  using: 'node20'
  main: 'dist/index.js'
